# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Ironman.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Ironman.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\rIronman.proto\x12\nhelloworld\"\x1b\n\x0bInitCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tInitReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\rRenderCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0bRenderReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\tRegistMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"!\n\x0fRegistResultMsg\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1a\n\nAddressMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10\x41\x64\x64ressReturnMsg\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t2\x97\x01\n\rBackendRender\x12?\n\x0bInitHandler\x12\x17.helloworld.InitCommand\x1a\x15.helloworld.InitReply\"\x00\x12\x45\n\rRenderHandler\x12\x19.helloworld.RenderCommand\x1a\x17.helloworld.RenderReply\"\x00\x32\x98\x01\n\x10SystemDispatcher\x12>\n\x06Regist\x12\x15.helloworld.RegistMsg\x1a\x1b.helloworld.RegistResultMsg\"\x00\x12\x44\n\nGetAddress\x12\x16.helloworld.AddressMsg\x1a\x1c.helloworld.AddressReturnMsg\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_INITCOMMAND = _descriptor.Descriptor(
  name='InitCommand',
  full_name='helloworld.InitCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.InitCommand.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=56,
)


_INITREPLY = _descriptor.Descriptor(
  name='InitReply',
  full_name='helloworld.InitReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.InitReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=86,
)


_RENDERCOMMAND = _descriptor.Descriptor(
  name='RenderCommand',
  full_name='helloworld.RenderCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.RenderCommand.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=117,
)


_RENDERREPLY = _descriptor.Descriptor(
  name='RenderReply',
  full_name='helloworld.RenderReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.RenderReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=149,
)


_REGISTMSG = _descriptor.Descriptor(
  name='RegistMsg',
  full_name='helloworld.RegistMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.RegistMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='helloworld.RegistMsg.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=193,
)


_REGISTRESULTMSG = _descriptor.Descriptor(
  name='RegistResultMsg',
  full_name='helloworld.RegistResultMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='helloworld.RegistResultMsg.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=228,
)


_ADDRESSMSG = _descriptor.Descriptor(
  name='AddressMsg',
  full_name='helloworld.AddressMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.AddressMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=256,
)


_ADDRESSRETURNMSG = _descriptor.Descriptor(
  name='AddressReturnMsg',
  full_name='helloworld.AddressReturnMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='helloworld.AddressReturnMsg.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=293,
)

DESCRIPTOR.message_types_by_name['InitCommand'] = _INITCOMMAND
DESCRIPTOR.message_types_by_name['InitReply'] = _INITREPLY
DESCRIPTOR.message_types_by_name['RenderCommand'] = _RENDERCOMMAND
DESCRIPTOR.message_types_by_name['RenderReply'] = _RENDERREPLY
DESCRIPTOR.message_types_by_name['RegistMsg'] = _REGISTMSG
DESCRIPTOR.message_types_by_name['RegistResultMsg'] = _REGISTRESULTMSG
DESCRIPTOR.message_types_by_name['AddressMsg'] = _ADDRESSMSG
DESCRIPTOR.message_types_by_name['AddressReturnMsg'] = _ADDRESSRETURNMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitCommand = _reflection.GeneratedProtocolMessageType('InitCommand', (_message.Message,), {
  'DESCRIPTOR' : _INITCOMMAND,
  '__module__' : 'Ironman_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.InitCommand)
  })
_sym_db.RegisterMessage(InitCommand)

InitReply = _reflection.GeneratedProtocolMessageType('InitReply', (_message.Message,), {
  'DESCRIPTOR' : _INITREPLY,
  '__module__' : 'Ironman_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.InitReply)
  })
_sym_db.RegisterMessage(InitReply)

RenderCommand = _reflection.GeneratedProtocolMessageType('RenderCommand', (_message.Message,), {
  'DESCRIPTOR' : _RENDERCOMMAND,
  '__module__' : 'Ironman_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.RenderCommand)
  })
_sym_db.RegisterMessage(RenderCommand)

RenderReply = _reflection.GeneratedProtocolMessageType('RenderReply', (_message.Message,), {
  'DESCRIPTOR' : _RENDERREPLY,
  '__module__' : 'Ironman_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.RenderReply)
  })
_sym_db.RegisterMessage(RenderReply)

RegistMsg = _reflection.GeneratedProtocolMessageType('RegistMsg', (_message.Message,), {
  'DESCRIPTOR' : _REGISTMSG,
  '__module__' : 'Ironman_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.RegistMsg)
  })
_sym_db.RegisterMessage(RegistMsg)

RegistResultMsg = _reflection.GeneratedProtocolMessageType('RegistResultMsg', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRESULTMSG,
  '__module__' : 'Ironman_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.RegistResultMsg)
  })
_sym_db.RegisterMessage(RegistResultMsg)

AddressMsg = _reflection.GeneratedProtocolMessageType('AddressMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSMSG,
  '__module__' : 'Ironman_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.AddressMsg)
  })
_sym_db.RegisterMessage(AddressMsg)

AddressReturnMsg = _reflection.GeneratedProtocolMessageType('AddressReturnMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSRETURNMSG,
  '__module__' : 'Ironman_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.AddressReturnMsg)
  })
_sym_db.RegisterMessage(AddressReturnMsg)


DESCRIPTOR._options = None

_BACKENDRENDER = _descriptor.ServiceDescriptor(
  name='BackendRender',
  full_name='helloworld.BackendRender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=296,
  serialized_end=447,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitHandler',
    full_name='helloworld.BackendRender.InitHandler',
    index=0,
    containing_service=None,
    input_type=_INITCOMMAND,
    output_type=_INITREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RenderHandler',
    full_name='helloworld.BackendRender.RenderHandler',
    index=1,
    containing_service=None,
    input_type=_RENDERCOMMAND,
    output_type=_RENDERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKENDRENDER)

DESCRIPTOR.services_by_name['BackendRender'] = _BACKENDRENDER


_SYSTEMDISPATCHER = _descriptor.ServiceDescriptor(
  name='SystemDispatcher',
  full_name='helloworld.SystemDispatcher',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=450,
  serialized_end=602,
  methods=[
  _descriptor.MethodDescriptor(
    name='Regist',
    full_name='helloworld.SystemDispatcher.Regist',
    index=0,
    containing_service=None,
    input_type=_REGISTMSG,
    output_type=_REGISTRESULTMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAddress',
    full_name='helloworld.SystemDispatcher.GetAddress',
    index=1,
    containing_service=None,
    input_type=_ADDRESSMSG,
    output_type=_ADDRESSRETURNMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSTEMDISPATCHER)

DESCRIPTOR.services_by_name['SystemDispatcher'] = _SYSTEMDISPATCHER

# @@protoc_insertion_point(module_scope)
